Feat: Textboxes with dinamic tags
Aviada-Labs/Aviada-ED pull request #30
Opened 2023-04-20 22:28 UTC by sofia-gastelum

# Fixes ticket #865c5hhac

## Problem Description
Created text input atom

## Checklist 
- [ ] Passes eslint linter 
- [ ] Passes backend integration tests 
- [ ] Added tests for this change 
- [ ] Added documentation for this change 
- [ ] Removed unused packages  

## Changes proposed in this pull request
Created a single textbox atom with its label. Font-size, color and textbox width are dynamic, added "danger" in colors for errors.

## Reviewers
- @aviada-rob 
- @aviada-andreazayas 
- @raulynzunza 

## Additional Comments

2023-04-20 22:28 UTC, aviada-fgp commented
Task linked: [CU-865c5hhac TextBox Fields](https://app.clickup.com/t/865c5hhac)

2023-04-21 01:48 UTC, jorgelabs requested changes

2023-04-21 01:48 UTC, jorgelabs commented on src/app/components/Atoms/TextboxInput/TextboxInput.tsx
> +  color: "text-secondary" | "text-light" | "text-danger" | "";
Use more precise types for the properties, Instead of using string types for "color" and "size", you can create specific types for those values. For example:
```
type Color = "text-secondary" | "text-light" | "text-danger" | "";
type Size = "text-sm" | "text-base" | "text-xl" | "";
```
Then, you can use these types in the interface definition:
```
export interface ITextboxInput {
  name: string;
  width: string;
  color: Color;
  size: Size;
}
```

2023-04-21 01:48 UTC, jorgelabs commented on src/app/components/Atoms/TextboxInput/TextboxInput.tsx
> +      <input type="text" value="name" className={` mt-1 block ${width} px-3 py-2 bg-white border border-slate-300 rounded-md ${size} shadow-sm placeholder-slate-400` }/>
Remove the string "name" from the value of the "value" attribute:
You probably want this value to be dynamic and depend on the value of the "name" property.
```
<input
  type="text"
  value={name}
  className={`mt-1 block ${width} px-3 py-2 bg-white border border-slate-300 rounded-md ${size} shadow-sm placeholder-slate-400`}
/>
```

2023-04-21 01:48 UTC, jorgelabs commented on src/app/components/Atoms/TextboxInput/TextboxInput.module.css
> +.container {
Is this file going to be used?, in case you don't remove it please

2023-04-21 01:48 UTC, jorgelabs commented on src/app/components/Atoms/TextboxInput/TextboxInput.stories.tsx
> +  title: "templates/TextboxInput",
Change the root of this component following the atomic design methodology

2023-04-21 02:16 UTC, Jorgect99 commented on src/app/components/Atoms/TextboxInput/TextboxInput.mocks.ts
> +  size: "",
What is the reason that you are not setting a default value of this properties?

2023-04-21 02:19 UTC, Jorgect99 commented on src/app/components/Atoms/TextboxInput/TextboxInput.mocks.ts
> +  size: "",
Or is correct the empty value on this variables?

2023-04-21 02:37 UTC, sofia-gastelum commented on src/app/components/Atoms/TextboxInput/TextboxInput.tsx
> +  color: "text-secondary" | "text-light" | "text-danger" | "";
how should this be done? on a separate file?

2023-04-21 02:38 UTC, sofia-gastelum commented on src/app/components/Atoms/TextboxInput/TextboxInput.tsx
> +      <input type="text" value="name" className={` mt-1 block ${width} px-3 py-2 bg-white border border-slate-300 rounded-md ${size} shadow-sm placeholder-slate-400` }/>
done

2023-04-21 02:38 UTC, sofia-gastelum commented on src/app/components/Atoms/TextboxInput/TextboxInput.module.css
> +.container {
done

2023-04-21 02:38 UTC, sofia-gastelum commented on src/app/components/Atoms/TextboxInput/TextboxInput.stories.tsx
> +  title: "templates/TextboxInput",
done

2023-04-21 02:38 UTC, sofia-gastelum commented on src/app/components/Atoms/TextboxInput/TextboxInput.mocks.ts
> +  size: "",
fixed it

2023-04-21 04:56 UTC, jorgelabs commented on src/app/components/Atoms/TextboxInput/TextboxInput.tsx
> +  color: "text-secondary" | "text-light" | "text-danger" | "";
In the same file, something like this:
```
type Color = "text-secondary" | "text-light" | "text-danger" | "";
type Size = "text-sm" | "text-base" | "text-xl" | "";
export interface ITextboxInput {
  name: string;
  width: string;
  color: Color;
  size: Size;
}
```

2023-04-21 18:25 UTC, sofia-gastelum commented on src/app/components/Atoms/TextboxInput/TextboxInput.tsx
> +  color: "text-secondary" | "text-light" | "text-danger" | "";
done

2023-04-21 18:25 UTC, jorgelabs approved these changes
🚀

2023-05-01 19:04 UTC, merged