Refactor: CU-865c5hgrw: UI Component Avatar Atom
Aviada-Labs/Aviada-ED pull request #36
Opened 2023-04-24 20:31 UTC by esmemee

# Fixes ticket [#865c5hgrw](https://app.clickup.com/t/865c5hgrw)

## Problem Description
Avatar Icon needed a white border

## Checklist 
- [ ] Passes eslint linter 
- [ ] Passes backend integration tests 
- [ ] Added tests for this change 
- [ ] Added documentation for this change 
- [ ] Removed unused packages  

## Changes proposed in this pull request

## Reviewers
- @aviada-andreazayas 
- @aviada-rob 

## Additional Comments

2023-04-25 20:59 UTC, jorgelabs requested changes

2023-04-25 20:59 UTC, jorgelabs commented on src/app/components/Atoms/AvatarAtom/AvatarAtom.tsx
> +          alt=""
Will this property not be used? If not, please delete it

2023-04-26 16:53 UTC, esmemee commented on src/app/components/Atoms/AvatarAtom/AvatarAtom.tsx
> +          alt=""
Fixed it :)

2023-04-26 18:24 UTC, esmemee commented on src/app/components/Atoms/AvatarAtom/AvatarAtom.tsx
> +          height={`${heightSize}`}
it did, thank u

2023-04-26 18:36 UTC, jorgelabs approved these changes

2023-04-26 18:37 UTC, merged