Refactor: CU-865c5hhb2: icons
Aviada-Labs/Aviada-ED pull request #37
Opened 2023-04-26 17:02 UTC by raulynzunza

# Fixes ticket [#CU-865c5hhb2](https://app.clickup.com/t/CU-865c5hhb2)

## Problem Description
Change an icon and add colors to different icons

## Checklist 
- [x] Passes eslint linter 
- [ ] Passes backend integration tests 
- [ ] Added tests for this change 
- [ ] Added documentation for this change 
- [ ] Removed unused packages  

## Changes proposed in this pull request
Change and add missing colors to different icons

## Reviewers
- @aviada-rob 
- @jorgelabs 
- @aviada-andreazayas 
- @eduardoMtzCh 

## Additional Comments

2023-04-26 17:02 UTC, aviada-fgp commented
Task linked: [CU-865c5hhb2 Icons](https://app.clickup.com/t/865c5hhb2)

2023-04-26 17:08 UTC, jorgelabs requested changes

2023-04-26 17:08 UTC, jorgelabs commented on src/app/components/Atoms/Icons/ErrorIcons/ErrorSimpleIcon/ErrorSimpleIcon.tsx
> +  color: "text-light" | "text-secondary" | "text-blue-primary" | "text-danger";
Use more precise types for the properties, Instead of using string types for "color" and "size", you can create specific types for those values. For example:
```
type Size = "text-sm" | "text-base" | "text-l" | "text-xl" | "text-2xl";
type Color = "text-light" | "text-secondary" | "text-blue-primary" | "text-danger";
````
Then, you can use these types in the interface definition:
```
export interface IErrorSimpleIcon {
  size: Size;
  color: Color;
}
```
You can make this change in all the files you modified

2023-04-26 17:33 UTC, JoHena commented on src/app/components/Atoms/Icons/ErrorIcons/ErrorSimpleIcon/ErrorSimpleIcon.tsx
> +  color: "text-light" | "text-secondary" | "text-blue-primary" | "text-danger";
Since this is used in many components, wouldn't it be better to add it to an external file like this?

`export type Size = "text-sm" | "text-base" | "text-l" | "text-xl" | "text-2xl;"
 type Color = "text-light" | "text-secondary" | "text-blue-primary" | "text-danger";`

And simply import them into where it's needed, that way if we need to add more colors we wouldn't have to modify every single instance. We already have one for reused interfaces, the same file can be used.

`import { Size, Color } from "../typing";

export interface IExpandMore {
  size: Size;
  color: Color;
}`

2023-04-26 17:34 UTC, jorgelabs commented on src/app/components/Atoms/Icons/ErrorIcons/ErrorSimpleIcon/ErrorSimpleIcon.tsx
> +  color: "text-light" | "text-secondary" | "text-blue-primary" | "text-danger";
Yeah

2023-04-26 17:54 UTC, raulynzunza commented on src/app/components/Atoms/Icons/ErrorIcons/ErrorSimpleIcon/ErrorSimpleIcon.tsx
> +  color: "text-light" | "text-secondary" | "text-blue-primary" | "text-danger";
Fixed it

2023-04-27 18:05 UTC, aviada-andreazayas approved these changes

2023-04-27 18:12 UTC, merged