Feat: Cu-865c5hh4w: UI components login box
Aviada-Labs/Aviada-ED pull request #54
Opened 2023-05-04 20:24 UTC by AndresOL2001

# Fixes ticket [#t865c5hh4w](https://app.clickup.com/t/865c5hh4w)

## Checklist 
- [ ] Passes eslint linter 
- [ ] Passes backend integration tests 
- [ ] Added tests for this change 
- [ ] Added documentation for this change 
- [ ] Removed unused packages  

## Changes proposed in this pull request
Login Component box added

## Reviewers
- @aviada-rob 
- @eduardoMtzCh 
- @jorgelabs 
- @aviada-andreazayas

2023-05-04 20:25 UTC, aviada-fgp commented
Task linked: [CU-865c5hh4w UI Components Login Box](https://app.clickup.com/t/865c5hh4w)

2023-05-04 20:34 UTC, aviada-andreazayas requested changes
Remove the tests for the other components that are not in the Login Box and add them on their own PR's please 😄

2023-05-04 20:54 UTC, AndresOL2001 commented
Ready

2023-05-04 21:08 UTC, aviada-andreazayas requested changes

2023-05-04 23:23 UTC, AndresOL2001 commented on src/app/components/Organisms/Login/Login.mocks.ts
> +  AlertError: true,
Done

2023-05-04 23:23 UTC, AndresOL2001 commented on src/app/components/Organisms/Login/Login.tsx
> +  AlertError: boolean;
Done

2023-05-05 16:28 UTC, aviada-andreazayas approved these changes

2023-05-05 16:29 UTC, merged