Feat : CU-865c8m0vm : Create dashboard
Aviada-Labs/Aviada-ED pull request #55
Opened 2023-05-04 21:09 UTC by JoHena

# Fixes ticket [#865c8m0vm](https://app.clickup.com/t/865c8m0vm)

## Problem Description
Create the Dashboard from the available components

## Checklist 
- [x] Passes eslint linter 
- [ ] Passes backend integration tests 
- [x] Added tests for this change 
- [x] Added documentation for this change 
- [ ] Removed unused packages  

## Changes proposed in this pull request
Create Dashboard on /dashboard URL
Create RoutingNav component
Add Google Fonts Import

## Reviewers
- @raulynzunza 
- @jorgelabs 
- @aviada-andreazayas 
- @aviada-fgp 

## Additional Comments

2023-05-04 21:09 UTC, aviada-fgp commented
Task linked: [CU-865c8m0vm Create Dashboard Component](https://app.clickup.com/t/865c8m0vm)

2023-05-05 16:59 UTC, raulynzunza approved these changes

2023-05-05 17:02 UTC, raulynzunza approved these changes

2023-05-05 19:42 UTC, aviada-andreazayas requested changes

2023-05-05 19:42 UTC, aviada-andreazayas commented on src/app/dashboard/layout.tsx
> +            { urlName: "Home", href: "/Dashboard" },
In the design the urlName is Dashboard and the href should be "/dashboard" all in lower case

2023-05-05 19:42 UTC, aviada-andreazayas commented on src/app/dashboard/layout.tsx
> +        <RoutingNav
The font color of the routing nav should be secondary (currently is black)

2023-05-05 19:42 UTC, aviada-andreazayas commented on src/app/components/Molecules/Hero/Hero.tsx
> +      <h1 className={"text-[1.5rem] absolute left-[28rem] text-light font-serif"}>
The font-weight should be bold

2023-05-05 19:48 UTC, JoHena commented on src/app/dashboard/layout.tsx
> +            { urlName: "Home", href: "/Dashboard" },
Fixed all hrefs

2023-05-05 19:51 UTC, JoHena commented on src/app/components/Molecules/Hero/Hero.tsx
> +      <h1 className={"text-[1.5rem] absolute left-[28rem] text-light font-serif"}>
Changed font to bold

2023-05-05 19:51 UTC, JoHena commented on src/app/dashboard/layout.tsx
> +        <RoutingNav
Changed font color to secondary

2023-05-05 19:57 UTC, aviada-andreazayas approved these changes

2023-05-05 19:58 UTC, merged